name       : google-play-music-desktop-player
version    : 4.4.0
release    : 5
source     :
    - https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/archive/v4.4.0.tar.gz : 4f0ee214fa32945715a5a456698d7bc7e1de44ccf9c8fd247b3607599a40bcff
license    : MIT
component  : multimedia.audio
networking : yes
summary    : A beautiful cross platform Desktop Player for Google Play Music
description: |
    A beautiful cross platform Desktop Player for Google Play Music
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-compat-libdns_sd)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - git
    - nodejs
rundeps    :
    - nodejs
setup      : |
    npm install
build      : |
    npm run build
install    : |
    npm run package:linux:64
    install -dm00644 $installdir/usr/bin
    install -Dm00644 $pkgfiles/gpmdp.desktop $installdir/usr/share/applications/gpmdp.desktop
    install -dm00644 $installdir/usr/share/gpmdp
    install -Dm00644 build/assets/img/main.png $installdir/usr/share/pixmaps/gpmdp.png
    cp -R dist/"Google Play Music Desktop Player-linux-x64"/* $installdir/usr/share/gpmdp/
    ln -s /usr/share/gpmdp/"Google Play Music Desktop Player" $installdir/usr/bin/gpmdp
